name: zanshin
description: A cross-platform Pomodoro

publish_to: 'none'

version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

#####################################################################
#####################################################################

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_vibrate: ^1.3.0
  font_awesome_flutter: ^9.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  just_audio: ^0.9.18
  percent_indicator: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.3.3
  hive_generator: ^1.1.1

#####################################################################
#####################################################################

flutter:

  uses-material-design: true

  assets:
    - assets/alarm/
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito_regular.ttf
        - asset: assets/fonts/nunito_bold.ttf
          weight: 600
        - asset: assets/fonts/nunito_extra_bold.ttf
          weight: 900

#####################################################################
#####################################################################

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

#####################################################################
#####################################################################

flutter_native_splash:

  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove

  # Background color
  color: "#ffffff"
  #color_dark: "#042a49"

  # OR an Image
  #background_image: "assets/background.png"
  #background_image_dark: "assets/dark-background.png"

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/images/app_icon.png
  #image_dark: assets/splash-invert.png

  # This property allows you to specify an image used as branding in the splash screen. It must be
  # a png file. Currently, it is only supported for Android and iOS.
  #branding: assets/dart.png
  #branding_dark: assets/dart_dark.png

  # Positioning: (default) bottom, bottomRight or bottomLeft.
  #branding_mode: bottom

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  android: false
  ios: false
  #web: false

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center

  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center

  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter. Has no affect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  #fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'